#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alan.coopersmith@oracle.com)
#
Name     : libpciaccess
Version  : 0.17
Release  : 24
URL      : https://www.x.org/releases/individual/lib/libpciaccess-0.17.tar.gz
Source0  : https://www.x.org/releases/individual/lib/libpciaccess-0.17.tar.gz
Source1  : https://www.x.org/releases/individual/lib/libpciaccess-0.17.tar.gz.sig
Summary  : Library providing generic access to the PCI bus and devices.
Group    : Development/Tools
License  : MIT
Requires: libpciaccess-lib = %{version}-%{release}
Requires: libpciaccess-license = %{version}-%{release}
BuildRequires : buildreq-meson
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32zlib)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(zlib)

%description
xorg/lib/libpciaccess - Generic PCI access library
--------------------------------------------------

%package dev
Summary: dev components for the libpciaccess package.
Group: Development
Requires: libpciaccess-lib = %{version}-%{release}
Provides: libpciaccess-devel = %{version}-%{release}
Requires: libpciaccess = %{version}-%{release}

%description dev
dev components for the libpciaccess package.


%package dev32
Summary: dev32 components for the libpciaccess package.
Group: Default
Requires: libpciaccess-lib32 = %{version}-%{release}
Requires: libpciaccess-dev = %{version}-%{release}

%description dev32
dev32 components for the libpciaccess package.


%package lib
Summary: lib components for the libpciaccess package.
Group: Libraries
Requires: libpciaccess-license = %{version}-%{release}

%description lib
lib components for the libpciaccess package.


%package lib32
Summary: lib32 components for the libpciaccess package.
Group: Default
Requires: libpciaccess-license = %{version}-%{release}

%description lib32
lib32 components for the libpciaccess package.


%package license
Summary: license components for the libpciaccess package.
Group: Default

%description license
license components for the libpciaccess package.


%prep
%setup -q -n libpciaccess-0.17
cd %{_builddir}/libpciaccess-0.17
pushd ..
cp -a libpciaccess-0.17 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666099246
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../build32;
make %{?_smp_mflags} check || : || :

%install
export SOURCE_DATE_EPOCH=1666099246
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libpciaccess
cp %{_builddir}/libpciaccess-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libpciaccess/be0802d65a8579a7719dc204057628d1d865d3d2 || :
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/pciaccess.h
/usr/lib64/libpciaccess.so
/usr/lib64/pkgconfig/pciaccess.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libpciaccess.so
/usr/lib32/pkgconfig/32pciaccess.pc
/usr/lib32/pkgconfig/pciaccess.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpciaccess.so.0
/usr/lib64/libpciaccess.so.0.11.1

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libpciaccess.so.0
/usr/lib32/libpciaccess.so.0.11.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libpciaccess/be0802d65a8579a7719dc204057628d1d865d3d2
